name: Publish to JSR

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - run: npx jsr publish
